language: go
sudo: false
go:
  - 1.6.2
os:
  - linux
  - windows
#  - osx
env:
- BIN_POSTFIX=$(test "$TRAVIS_OS_NAME" == "windows" && echo ".exe")
script:
  - go get -t -v ./...
  - go build -o gomusic$BINPOSTFIX gomusic.go
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - gomusic$BINPOSTFIX
  skip_cleanup: true
  on:
    tags: true