language: go
sudo: required
go:
  - 1.6.2
before_install:
  - sudo apt-get install -y upx-ucl
install:
  - go get -t -v ./...
  - go get github.com/mitchellh/gox
  - go get github.com/inconshreveable/mousetrap
  - go get github.com/pwaller/goupx
  - go install github.com/mitchellh/gox
script:
  - gox -os "linux windows" -arch "amd64 386" -output="binaries/{{.OS}}/{{.Arch}}/gomusic" -ldflags "-s -w"
after_success:
  - zip -r gomusic-all.zip binaries
  - tar -cvzf gomusic-all.tar.gz binaries
  - upx -9 -q binaries/linux/amd64/gomusic
  - cp binaries/windows/amd64/gomusic.exe ./
  - cp binaries/linux/amd64/gomusic ./
  - zip -r gomusic-windows-amd64.zip gomusic.exe
  - tar -cvzf gomusic-linux-amd64.tar.gz gomusic
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - gomusic-all.zip
    - gomusic-all.tar.gz
    - gomusic-windows-amd64.zip
    - gomusic-linux-amd64.tar.gz
  skip_cleanup: true
  overwrite: true