language: go
sudo: false
go:
  - 1.6.2
os:
  - linux
  - windows
#  - osx
script:
  - go get -t -v ./...
  - go build -o gomusic-$TRAVIS_OS_NAME gomusic.go
before_deploy:
  - ls
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - gomusic-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true